name: Build and Push Docker Images

on:
  push:
    branches:
      - main

env:
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  AWS_REGION: ap-south-1
  FRONTEND_REPO: ${{ vars.FRONTEND_REPO }}
  BACKEND_REPO: ${{ vars.BACKEND_REPO }}

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Show Repository Structure
        run: |
          pwd
          ls -R

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Frontend Image
        run: |
          docker build -t frontend-image ./wpoms_web

      - name: Build Backend Image
        run: |
          docker build -t backend-image ./wpoms_admin

      - name: Tag Frontend Image
        run: |
          docker tag frontend-image:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:${{ github.sha }}

      - name: Tag Backend Image
        run: |
          docker tag backend-image:latest \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:${{ github.sha }}

      - name: Push Frontend Image
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$FRONTEND_REPO:${{ github.sha }}

      - name: Push Backend Image
        run: |
          docker push \
          $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$BACKEND_REPO:${{ github.sha }}